### ISSUE TITLE
Injected 

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/openapi-forge-csharp#44]
The API client classes take a `Configuration` instance in their constructor, which is provided by the DI framework. However, in order to provide configuration, the `Startup.RegisterApiClient` function takes a user-supplied config instance:

~~~
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using OpenApiForge;

var services = new ServiceCollection();
services.Add(new ServiceDescriptor(typeof(Configuration), typeof(Configuration), ServiceLifetime.Scoped));

// this config object is not the same as the one injected via the DI framework
var config = new Configuration() {
  BasePath = "https://petstore3.swagger.io",
};

Startup.RegisterApiClient(services, config);
~~~

As a result, the user-supplied values are not respected by the API client classes.

**Comment by murcikan-scottlogic** [comment]
As discussed, one can use to supply custom values as part of the configuration: 
`services.Add(new ServiceDescriptor(typeof(Configuration), new Configuration{  BasePath = "https://petstore3.swagger.io" });`
